---
title: "salariesRatio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#library("sm")
#library("vioplot")
#library("Hmisc")

numResamples = 10000
```

```{r load, echo=FALSE}

# load the data
# set your path
salaries = read.csv("your_path/uclaUscSalaries.csv")

numSamples = nrow(salaries) # how many datapoints do we have?

# format the data
uscSalaries = salaries$usc
uclaSalaries = salaries$ucla
irvineSalaries = salaries$irvine
```

# Significance
## Paired null hypothesis permutation test

```{r paired significance bootstrap}

salariesForPerms = salaries[,c("ucla","irvine")]

# what did original data show?
origEffectSize = mean( salariesForPerms$irvine - salariesForPerms$ucla )

indices = 1:nrow(salaries) # list all rows
testStatisticDistribution = rep(NA,numResamples)
for (i in 1 : numResamples) {
  # simulate chance: for each row, randomly swap samples
  shouldFlipRows = runif( nrow(salariesForPerms) ) > .5
  rowsToFlip = which (shouldFlipRows)
  salariesForPerms[rowsToFlip,1:2] = salariesForPerms[rowsToFlip,2:1]
  
  # calculate statistic
  testStatisticDistribution[i] = mean(salariesForPerms$irvine - salariesForPerms$ucla)
} 

# calculate p-value
pval <- (sum(testStatisticDistribution >= origEffectSize) + 
           sum(testStatisticDistribution <= -origEffectSize) ) / (numResamples)
sprintf("null distribution; observed effect %g, pval of observed effect %g", origEffectSize, pval)
```

## paired null hist
```{r paired null hist, echo=FALSE}

par(mfrow=c(1,1))

# bounds
SortedtestStatisticDistribution <- sort(testStatisticDistribution)
testStatisticLeftBound <- SortedtestStatisticDistribution[.025*numResamples]
testStatisticRightBound <- SortedtestStatisticDistribution[.975*numResamples]

sprintf("null distribution CI: (%g, %g): observed effect %g, pval of observed effect %g", testStatisticLeftBound, testStatisticRightBound, origEffectSize, pval)

hist(testStatisticDistribution, 40, xlab="Test Statistic", main="Histogram of Null Distribution")
abline(v=origEffectSize, col="green")
abline(v=testStatisticLeftBound, col="red")
abline(v=testStatisticRightBound, col="red")
```

# Magnitude
```{r null mag bootstrap}

indices = 1:numSamples
testStatisticDistribution = rep(NA,numResamples)

for (i in 1 : numResamples) {
  #resample
  bootDataInds = sample (indices, length(indices), replace = T)
  bootData = salaries[bootDataInds,]
  
  # calculate statistic
  testStatisticDistribution[i] = mean(bootData$irvine) - mean(bootData$ucla) # calc fractional salaries
}

## confidence intervals
sorted_mean <- sort(testStatisticDistribution)
testStatisticLeftBound <- sorted_mean[.025*numResamples]
testStatisticRightBound <- sorted_mean[.975*numResamples]
```

## plots
```{r paired hist, echo=FALSE}

par(mfrow=c(1,1))

sprintf("effect size %g (%g, %g)", origEffectSize, testStatisticLeftBound, testStatisticRightBound)

hist(testStatisticDistribution, 40, xlab="Test Statistic", main="Histogram of Bootstraps")
abline(v=origEffectSize, col="blue")
abline(v=testStatisticLeftBound, col="red")
abline(v=testStatisticRightBound, col="red")
```